### ISSUE TITLE
Docker exec doesn't work

### ISSUE THREAD

**Issue by qqpann** [minerllabs/basalt_intro_track_2022_competition_submission_template#1]
This repo's dockerfile gives me the same kind of issue as described in https://github.com/minerllabs/basalt_2022_competition_submission_template/issues/1

```sh
aicrowd@a62f3bf05146:~$ ls
Dockerfile       LICENSE    aicrowd.json  config.py        run.py   train
Dockerfile-full  README.md  apt.txt       environment.yml  test.py
aicrowd@a62f3bf05146:~$ python run.py 
2022-08-25 15:01:28 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] INFO Starting Minecraft process: ['/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/../MCP-Reborn/launchClient.sh', '-port', '9375', '-env', '-runDir', '/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/../MCP-Reborn/run']
2022-08-25 15:01:28 a62f3bf05146 process_watcher[22] INFO Launching process watcher daemonizer.
/home/aicrowd/.conda/envs/minerl/lib/python3.7/runpy.py:125: RuntimeWarning: 'minerl.utils.process_watcher' found in sys.modules after import of package 'minerl.utils', but prior to execution of 'minerl.utils.process_watcher'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2022-08-25 15:01:29 a62f3bf05146 process_watcher[22] INFO Process watcher daemonizer launched successfully.
2022-08-25 15:01:29 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG /home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/../MCP-Reborn
2022-08-25 15:01:37 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-08-25 15:01:37 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-08-25 15:01:37 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-08-25 15:01:39 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG [15:01:39] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR [15:01:40] [Render thread/ERROR]: Failed to verify authentication!
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG [15:01:40] [Render thread/INFO]: Setting user: Player408
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG [15:01:40] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG ---- Minecraft Crash Report ----
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG // Don't do that.
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG Time: 8/25/22 3:01 PM
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG Description: Initializing game
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x10008]140432893718208
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	at net.minecraft.client.main.Main.main(Main.java:154)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG A detailed walkthrough of the error, its code path and all known details is as follows:
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG ---------------------------------------------------------------------------------------
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG -- Head --
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG Thread: Render thread
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG Stacktrace:
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG -- Initialization --
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG Details:
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG Stacktrace:
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	at net.minecraft.client.main.Main.main(Main.java:154)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG -- System Details --
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG Details:
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	Minecraft Version: 1.16.5
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	Minecraft Version ID: 1.16.5
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	Operating System: Linux (amd64) version 5.15.0-46-generic
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	Java Version: 1.8.0_342, Private Build
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	Memory: 735719832 bytes (701 MB) / 1148715008 bytes (1095 MB) up to 3817865216 bytes (3641 MB)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	CPUs: 12
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	JVM Flags: 1 total; -Xmx4G
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	Launched Version: ~~NULL~~
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	Backend library: LWJGL version 3.2.2 SNAPSHOT
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	Backend API: NO CONTEXT
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	GL Caps: 
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	Using VBOs: Yes
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	Is Modded: Very likely; Jar signature invalidated
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	Type: Client (map_client.txt)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG 	CPU: <unknown>
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] DEBUG #@!@# Game crashed! Crash report saved to: #@!@# /home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/MCP-Reborn/./crash-reports/crash-2022-08-25_15.01.40-client.txt
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR /home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/../MCP-Reborn
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR SLF4J: Defaulting to no-operation (NOP) logger implementation
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR [15:01:39] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR [15:01:40] [Render thread/ERROR]: Failed to verify authentication!
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR [15:01:40] [Render thread/INFO]: Setting user: Player408
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR [15:01:40] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR ---- Minecraft Crash Report ----
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR // Don't do that.
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR Time: 8/25/22 3:01 PM
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR Description: Initializing game
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x10008]140432893718208
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	at net.minecraft.client.main.Main.main(Main.java:154)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR A detailed walkthrough of the error, its code path and all known details is as follows:
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR ---------------------------------------------------------------------------------------
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR -- Head --
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR Thread: Render thread
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR Stacktrace:
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR -- Initialization --
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR Details:
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR Stacktrace:
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	at net.minecraft.client.main.Main.main(Main.java:154)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR -- System Details --
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR Details:
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	Minecraft Version: 1.16.5
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	Minecraft Version ID: 1.16.5
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	Operating System: Linux (amd64) version 5.15.0-46-generic
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	Java Version: 1.8.0_342, Private Build
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	Memory: 735719832 bytes (701 MB) / 1148715008 bytes (1095 MB) up to 3817865216 bytes (3641 MB)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	CPUs: 12
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	JVM Flags: 1 total; -Xmx4G
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	Launched Version: ~~NULL~~
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	Backend library: LWJGL version 3.2.2 SNAPSHOT
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	Backend API: NO CONTEXT
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	GL Caps: 
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	Using VBOs: Yes
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	Is Modded: Very likely; Jar signature invalidated
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	Type: Client (map_client.txt)
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR 	CPU: <unknown>
2022-08-25 15:01:40 a62f3bf05146 minerl.env.malmo.instance.7ba76b[22] ERROR #@!@# Game crashed! Crash report saved to: #@!@# /home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/MCP-Reborn/./crash-reports/crash-2022-08-25_15.01.40-client.txt
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    test.main()
  File "/home/aicrowd/test.py", line 24, in main
    obs = env.reset()
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/gym/wrappers/time_limit.py", line 27, in reset
    return self.env.reset(**kwargs)
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/herobraine/env_specs/obtain_specs.py", line 60, in reset
    obs = super().reset()
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/gym/core.py", line 251, in reset
    return self.env.reset(**kwargs)
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/_singleagent.py", line 22, in reset
    multi_obs = super().reset()
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/_multiagent.py", line 436, in reset
    self._setup_instances()
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/_multiagent.py", line 539, in _setup_instances
    self.instances.extend([f.result() for f in instance_futures])
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/_multiagent.py", line 539, in <listcomp>
    self.instances.extend([f.result() for f in instance_futures])
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/_multiagent.py", line 805, in _get_new_instance
    instance.launch(replaceable=self._is_fault_tolerant)
  File "/home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/malmo.py", line 428, in launch
    error_str + "\n\nMinecraft process finished unexpectedly. There was an error with Malmo.")
EOFError: /home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/env/../MCP-Reborn
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[15:01:39] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[15:01:40] [Render thread/ERROR]: Failed to verify authentication!
[15:01:40] [Render thread/INFO]: Setting user: Player408
[15:01:40] [Render thread/INFO]: Backend library: LWJGL version 3.2.2 SNAPSHOT
---- Minecraft Crash Report ----
// Don't do that.

Time: 8/25/22 3:01 PM
Description: Initializing game

java.lang.IllegalStateException: Failed to initialize GLFW, errors: GLFW error during init: [0x10008]140432893718208
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)
	at net.minecraft.client.main.Main.main(Main.java:154)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at com.mojang.blaze3d.platform.GLX._initGlfw(GLX.java:80)
	at com.mojang.blaze3d.systems.RenderSystem.initBackendSystem(RenderSystem.java:586)
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:406)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:154)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 5.15.0-46-generic
	Java Version: 1.8.0_342, Private Build
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Private Build
	Memory: 735719832 bytes (701 MB) / 1148715008 bytes (1095 MB) up to 3817865216 bytes (3641 MB)
	CPUs: 12
	JVM Flags: 1 total; -Xmx4G
	Launched Version: ~~NULL~~
	Backend library: LWJGL version 3.2.2 SNAPSHOT
	Backend API: NO CONTEXT
	GL Caps: 
	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	CPU: <unknown>
#@!@# Game crashed! Crash report saved to: #@!@# /home/aicrowd/.conda/envs/minerl/lib/python3.7/site-packages/minerl/MCP-Reborn/./crash-reports/crash-2022-08-25_15.01.40-client.txt


Minecraft process finished unexpectedly. There was an error with Malmo.
aicrowd@a62f3bf05146:~$ 

```

**Comment by Miffyli** [comment]
Hey, answering here for completeness sake as well: this probably requires the use of xvfb to create a virtual buffer to run things on Docker images, especially on headless machines (ones without displays). After installing xvfb (e.g. `sudo apt install xvfb`), try `xvfb-run python your_script.py` (inside the Docker).
